title: geoffjay
tagline: 'Generic Blog'
url: "https://geoffjay.github.io"
email: geoff.jay@gmail.com
baseurl: ""

description: >
  Just another blog.

twitter_username: geoffjay
github_username:  geoffjay

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
author:
  name: 'Geoff Johnson'
  url: https://geoffjay.github.io
  github: https://github.com/geoffjay

paginate: 5

# Custom vars
version: 0.1.0

opendcs:
  url: https://open-dcs.github.io

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
